/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.codec.Base64;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.*;
/**
 *
 * @author ADMIN
 */
public class checkoutPage extends javax.swing.JFrame {

    /**
     * Creates new form checkoutPage
     */
    public checkoutPage() {
        initComponents();
        coutname.setEditable(false);
        coutemail.setEditable(false);
        coutNo.setEditable(false);
        coutppDay.setEditable(false);
        coutCin.setEditable(false);
        coutCout.setEditable(false);
        couttamount.setEditable(false);
        coutDays.setEditable(false);
        
    }
    int ID=0;
    String rmType;
    String Rno;
    String beds;
    String Query;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        coutsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        coutname = new javax.swing.JTextField();
        coutemail = new javax.swing.JTextField();
        coutCin = new javax.swing.JTextField();
        coutCout = new javax.swing.JTextField();
        coutDays = new javax.swing.JTextField();
        coutNo = new javax.swing.JTextField();
        coutppDay = new javax.swing.JTextField();
        couttamount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 120));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        coutsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 72, 142, -1));

        jButton1.setBackground(new java.awt.Color(45, 55, 63));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 71, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 151, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 151, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Customer Phone No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 151, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price Per Day");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 151, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Check In Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 265, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Check Out Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 265, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No of Stay Days");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 265, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 265, -1, -1));

        coutname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutname, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 184, 201, -1));

        coutemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 184, 201, -1));

        coutCin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutCin, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 298, 201, -1));

        coutCout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutCout, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 298, 201, -1));

        coutDays.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 298, 201, -1));

        coutNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 184, 201, -1));

        coutppDay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(coutppDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 184, 201, -1));

        couttamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(couttamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 298, 201, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Gender ", "Phone No", "Nationality", "Address", "Bed", "Room Type", "Cnic", "Check In Date", "Room No", "Price by Days"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 377, 1250, 212));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Check Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 336, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\project material\\coutp1.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
        ResultSet rs=select.getdata("select * from customercheckin where checkOut is NULL");
        DefaultTableModel tb=(DefaultTableModel)jTable1.getModel();
        tb.setRowCount(0);
        
        while(rs.next()){
        tb.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14)});
        }
        //rs.close();
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String rmNo=coutsearch.getText();
        try{
        ResultSet rs=select.getdata("select * from customercheckin where rmNo='"+rmNo+"' and checkOut is NULL");
        if(rs.next()){
        coutsearch.setEditable(false);
        ID=rs.getInt(1);
        coutname.setText(rs.getString(2));
        coutNo.setText(rs.getString(5));
        coutppDay.setText(rs.getString(14));
        coutCin.setText(rs.getString(12));
        
        SimpleDateFormat myFormat=new SimpleDateFormat("dd/MM/yyyy");
        Calendar cl=Calendar.getInstance();
        coutCout.setText(myFormat.format(cl.getTime()));
        String dateBeforeString=rs.getString(12);
        java.util.Date dateBefore=myFormat.parse(dateBeforeString);
        String dateAfterString=myFormat.format(cl.getTime());
        java.util.Date dateAfter=myFormat.parse(dateAfterString);
        long difference=dateAfter.getTime()-dateBefore.getTime();
        int noOfDaysStay=(int) (difference/(1000*60*60*24));
        if(noOfDaysStay==0)
            noOfDaysStay=1;
        coutDays.setText(String.valueOf(noOfDaysStay));
        float price=Float.parseFloat(coutppDay.getText());
        couttamount.setText(String.valueOf(noOfDaysStay*price));
        coutemail.setText(rs.getString(3));
        rmType=rs.getString(9);
        beds=rs.getString(8);
        }else
            JOptionPane.showMessageDialog(null, "Room Number Does Not Exist");
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fname=coutname.getText();
        String email=coutemail.getText();
        String price=coutppDay.getText();
        String mnumber=coutNo.getText();
        String checkin=coutCin.getText();
        String checkOut=coutCout.getText();
        String totalAmount=couttamount.getText();
        String noOfDaysStay=coutDays.getText();
         Rno=coutsearch.getText();
         Query="update customercheckin set noOfDaysStay='"+noOfDaysStay+"',checkOut='"+checkOut+"',totalAmount='"+totalAmount+"' where id='"+ID+"'";
         insertUpdateDelete.setData(Query,"");
         Query="update rooms set Status='Not Booked' where Rno='"+Rno+"'";
         insertUpdateDelete.setData(Query,"Check Out Successfully");
         
         String path="D:\\project material";
         com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
         try{
         PdfWriter.getInstance(doc, new FileOutputStream(path+""+ID+".pdf"));
         doc.open();
         Paragraph paragraph1=new Paragraph("                                        Al-Maawa Hotel Management System\n ");
         doc.add(paragraph1);
         Paragraph paragraph2=new Paragraph("****************************************************************************************************************");
         doc.add(paragraph2);
         Paragraph paragraph3=new Paragraph("\tBill ID: "+ID+"\nName:"+fname+"\nEmail:"+email+"\nMobile No:"+mnumber+"\n");
         doc.add(paragraph3);
         doc.add(paragraph2);
         Paragraph paragraph4=new Paragraph("Room Details:\nRoom Number:"+coutsearch.getText()+"\nRoom Type:"+rmType+"\nBeds:"+beds+"\nPrice Per Day:"+coutppDay.getText()+"\n");                  
         doc.add(paragraph4);
         doc.add(paragraph2);
         PdfPTable tb1=new PdfPTable(4);
         tb1.addCell("Check In Date:"+coutCin.getText());
         tb1.addCell("Check Out Date:"+checkOut);
         tb1.addCell("No Of Days Stay:  "+noOfDaysStay);
         tb1.addCell("Total Amount:"+totalAmount);
         doc.add(tb1);
         doc.add(paragraph2);
         Paragraph paragraph5=new Paragraph("THANK YOU\n ");
         doc.add(paragraph5);
         }catch(Exception e){
             e.printStackTrace();
         JOptionPane.showMessageDialog(null,e);
         }
         doc.close();
         int a=JOptionPane.showConfirmDialog(null,"Print Bill ?","Select",JOptionPane.YES_NO_OPTION);
         if(a==0){
         try{
         if((new File("D:\\project material"+ID+".pdf")).exists()){
             Process p=Runtime
                     .getRuntime()
                     .exec("rundll32 url.dll,FileProtocolHandler D:\\project material"+ID+".pdf");
         }else
                 System.out.println("File Does Not Exists");
         }catch(Exception e){
             e.printStackTrace();
         JOptionPane.showMessageDialog(null,e);
         }
         }
        setVisible(false);
        new checkoutPage().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkoutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkoutPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField coutCin;
    private javax.swing.JTextField coutCout;
    private javax.swing.JTextField coutDays;
    private javax.swing.JTextField coutNo;
    private javax.swing.JTextField coutemail;
    private javax.swing.JTextField coutname;
    private javax.swing.JTextField coutppDay;
    private javax.swing.JTextField coutsearch;
    private javax.swing.JTextField couttamount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
