
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
import javax.swing.JOptionPane;
import project.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class checkInPage extends javax.swing.JFrame {

    /**
     * Creates new form checkInPage
     */
    public checkInPage() {
        initComponents();
        cDate.setEditable(false);
        Rprice.setEditable(false);
        SimpleDateFormat myFormat=new SimpleDateFormat("dd/MM/yyyy");
        Calendar cl=Calendar.getInstance();
        cDate.setText(myFormat.format(cl.getTime()));
    }
         String Rno;
         String Rtype;
         String bed;
         String price;
         public void roomDetails(){
         croomNo.removeAllItems();
         Rprice.setText("");
         bed=(String)cbed.getSelectedItem();
         Rtype=(String)croomType.getSelectedItem();
         try{
             ResultSet rs=select.getdata("Select *from rooms where bed='"+bed+"' and Rtype='"+Rtype+"' and Status='Not Booked'");
             while(rs.next()){
             croomNo.addItem(rs.getString(1));
             } 
             }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
         
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        Cmnumber = new javax.swing.JTextField();
        Cgender = new javax.swing.JComboBox<>();
        cId = new javax.swing.JTextField();
        cnationality = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        cDate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Rprice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        croomType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbed = new javax.swing.JComboBox<>();
        croomNo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 120));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lithos Pro Regular", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 158, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cnic");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 297, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 369, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nationality");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 158, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 435, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 229, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check In Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 297, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 229, -1, -1));

        cname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 181, 310, -1));

        cemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 252, 310, -1));

        Cmnumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Cmnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 458, 310, -1));

        Cgender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(Cgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 392, 310, -1));

        cId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cId, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 320, 310, -1));

        cnationality.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cnationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 181, 310, -1));

        caddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 252, 310, -1));

        cDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(cDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 320, 310, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 367, -1, -1));

        Rprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Rprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 390, 320, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 296, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Room Type");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 227, -1, -1));

        croomType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        croomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        croomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(croomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 250, 320, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bed");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 158, -1, -1));

        cbed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        cbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbedActionPerformed(evt);
            }
        });
        getContentPane().add(cbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 181, 320, -1));

        croomNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        croomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croomNoActionPerformed(evt);
            }
        });
        getContentPane().add(croomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 319, 320, -1));

        jButton2.setBackground(new java.awt.Color(45, 55, 63));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Alote Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 431, -1, -1));

        jButton3.setBackground(new java.awt.Color(45, 55, 63));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Refresh");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 460, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\project material\\checkinpage.png")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void croomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croomTypeActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_croomTypeActionPerformed

    private void cbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbedActionPerformed
        // TODO add your handling code here:
        roomDetails();
    }//GEN-LAST:event_cbedActionPerformed

    private void croomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croomNoActionPerformed
        // TODO add your handling code here:
        Rno=(String)croomNo.getSelectedItem();
        try{
             ResultSet rs=select.getdata("Select *from rooms where Rno='"+Rno+"'");
             while(rs.next()){
             Rprice.setText(rs.getString(4));
             } 
             }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_croomNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
        //int id=1;
        String fname=cname.getText();
        String email=cemail.getText();
        String gender=(String)Cgender.getSelectedItem();
        String mnumber=Cmnumber.getText();
        String nationality=cnationality.getText();
        String address=caddress.getText();
        String Cnic=cId.getText();
        String checkin=cDate.getText();
        String beds=(String)cbed.getSelectedItem();
        String Rmtype=(String)croomType.getSelectedItem(); 
        String Rmno=(String)croomNo.getSelectedItem();
        String pricePerDay=Rprice.getText();
        
        String Query; 
       
//Query = "Select max(id) from customercheckin";
        
      
        
        //ResultSet rs=select.getdata(Query);
        //while(rs.next())
          // id=rs.getInt(1);
           //id=id+1;
             System.out.println("CNIC="+Cnic);
             System.out.println("C prize "+pricePerDay);
            // System.out.println("price="+price);
        if(!pricePerDay.equals(""))
        {
              System.out.println("first name"+fname); 
        Query="update rooms set Status='Booked' where Rno='"+Rmno+"'";
        insertUpdateDelete.setData(Query,"");
            
        Query="insert into customercheckin(fname,email,gender,mnumber,nationality,address,beds,Rmtype,Cnic,checkin,Rmno,pricePerDay) values('"+fname+"','"+email+"','"+gender+"','"+mnumber+"','"+nationality+"','"+address+"','"+beds+"','"+Rmtype+"','"+Cnic+"','"+checkin+"','"+Rmno+"','"+pricePerDay+"')";
        insertUpdateDelete.setData(Query,"Check-In Successfully");
        System.out.println("successfully done");
            setVisible(false);
            new checkInPage().setVisible(true);
        }    
        }catch(Exception e){
            e.printStackTrace();
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cgender;
    private javax.swing.JTextField Cmnumber;
    private javax.swing.JTextField Rprice;
    private javax.swing.JTextField cDate;
    private javax.swing.JTextField cId;
    private javax.swing.JTextField caddress;
    private javax.swing.JComboBox<String> cbed;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnationality;
    private javax.swing.JComboBox<String> croomNo;
    private javax.swing.JComboBox<String> croomType;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
